# Generated by Django 4.1.6 on 2023-02-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="event",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                fields=("id", "user", "event_type"), name="unique_event"
            ),
        ),
    ]
