# Generated by Django 4.1.6 on 2023-02-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0003_remove_event_unique_event_alter_event_event_type_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="event",
            name="unique_event",
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                fields=("id", "user", "event_type"), name="unique_event"
            ),
        ),
    ]
